### ISSUE TITLE
Some doubts

### ISSUE THREAD

**Issue by alwinsajip** [coolprashi06/excel_to_vcf#1]
Is it in working condition
What are its requirements
Can you please explain the installation and usage proccess of this in detail

**Comment by coolprashi06** [comment]
It’s a java utility. You can do code build using maven.
This requires you to setup ODBC datasource for the excel from which you want to create vcf file. You can do that from control panel on windows.

Also this requires you to give folder path where you want vcf files to be placed.

This utility only creates vcf for contacts presnt in excel file. 
If you’ve some diff requirement, you can download the code and make changes as you need and run it
